spring:
  jackson:
    serialization:
      writeDatesAsTimestamps: false

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3335/cpu_info
    username: cpu
    password: cpu
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    openInView: false
